public enum TokenType {
    // Single-character tokens.
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
  LEFT_BRACKET, RIGHT_BRACKET,

  // One or two character tokens.
  BANG, BANG_EQUAL,  // the ! operator
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  PLUSEQUAL, MINUSEQUAL,
  MULTEQUAL, DIVEQUAL,

  // Literals.
  IDENTIFIER, STRING, NUMBER, INT, DOUBLE, FLOAT, BOOLEAN,
  BYTE, LONG, SHORT, CHAR, ARGS,

  // Keywords.
  AND, CLASS, ELSE, FALSE, FOR, IF, NIL, OR,
  PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,
  PUBLIC, ABSTRACT, SYSTEM, OUT, PRINTLN, BREAK,
  CATCH, CONTINUE, CONST, DEFAULT, ENUM, EXTENDS,
  FINAL, FINALLY, INTERFACE, MAIN, PRIVATE, PROTECTED,
  STATIC, VOID, VOLATILE, THROW, TRY, DO, SWITCH, CASE,

  EOF
}