public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    LEFT_BRACKET, RIGHT_BRACKET, COLON,

    // One or two character tokens.
    BANG, BANG_EQUAL,  // the ! operator
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    PLUSEQUAL, MINUSEQUAL,
    MULTEQUAL, DIVEQUAL,
    PLUS_PLUS, MINUS_MINUS,


    // Literals.
    IDENTIFIER, STRING, NUMBER, INT, DOUBLE, FLOAT, BOOLEAN,
    BYTE, LONG, SHORT, CHAR,

    // Keywords.
    AND, AND_AND, CLASS, ELSE, FALSE, FOR, IF, NULL, OR,
    OR_OR, PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,
    PUBLIC, ABSTRACT, SYSTEM, OUT, PRINTLN, BREAK,
    CATCH, CONTINUE, CONST, DEFAULT, ENUM, EXTENDS,
    FINAL, FINALLY, INTERFACE, MAIN, PRIVATE, PROTECTED,
    STATIC, VOID, VOLATILE, THROW, THROWS, TRY, DO, SWITCH, CASE,
    IMPLEMENTS, PACKAGE, IMPORT, EXCEPTION, NEW, 

    EOF
}